import type { Metadata } from "next";
import { Ubuntu_Mono } from "next/font/google";
import "@/styles/globals.css";

const ubuntu = Ubuntu_Mono({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  );
}
